version: 2

project_name: local-ci

builds:
  - main: ./cmd/local-ci/
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: ["zip"]
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: local-ci
    directory: Casks
    homepage: "https://github.com/MrPuls/local-ci"
    description: "Run Docker-based CI pipelines locally"
    binaries:
      - local-ci
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/local-ci"]
          end
    repository:
      owner: MrPuls
      name: homebrew-local-ci
      token: "{{ .Env.PUBLISHER_TOKEN }}"
