package config

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

var matrixSafeRe = regexp.MustCompile(`^[a-zA-Z0-9_.-]+$`)

// ExpandMatrix returns the variants generated by a job's matrix definition.
// If the job has no matrix, it returns the job unchanged in a single-element
// slice. Each variant has a unique Name (suffixed with key.value pairs), a
// fresh Variables map containing the parent's variables plus the matrix
// values, and a MatrixGroup field set to the original job name.
func ExpandMatrix(job JobConfig) ([]JobConfig, error) {
	if len(job.Matrix) == 0 {
		return []JobConfig{job}, nil
	}

	var variants []JobConfig
	seen := make(map[string]bool)
	for entryIdx, entry := range job.Matrix {
		if err := validateMatrixEntry(entry, job.Name, entryIdx); err != nil {
			return nil, err
		}
		keys := sortedKeys(entry)
		for _, combo := range cartesianProduct(entry, keys) {
			v := cloneJobForVariant(job)
			v.MatrixGroup = job.Name
			parts := make([]string, 0, len(keys))
			for _, k := range keys {
				v.Variables[k] = combo[k]
				parts = append(parts, k+"."+combo[k])
			}
			v.Name = job.Name + "_" + strings.Join(parts, "_")
			if seen[v.Name] {
				return nil, fmt.Errorf("job %q: duplicate matrix variant %q", job.Name, v.Name)
			}
			seen[v.Name] = true
			variants = append(variants, v)
		}
	}
	return variants, nil
}

func validateMatrixEntry(entry MatrixEntry, jobName string, entryIdx int) error {
	if len(entry) == 0 {
		return fmt.Errorf("job %q: matrix entry %d is empty", jobName, entryIdx)
	}
	for k, values := range entry {
		if !matrixSafeRe.MatchString(k) {
			return fmt.Errorf("job %q: matrix key %q contains unsafe characters (allowed: a-zA-Z0-9_.-)", jobName, k)
		}
		if len(values) == 0 {
			return fmt.Errorf("job %q: matrix key %q has no values", jobName, k)
		}
		for _, val := range values {
			if !matrixSafeRe.MatchString(val) {
				return fmt.Errorf("job %q: matrix value %q for key %q contains unsafe characters (allowed: a-zA-Z0-9_.-)", jobName, val, k)
			}
		}
	}
	return nil
}

func sortedKeys(entry MatrixEntry) []string {
	keys := make([]string, 0, len(entry))
	for k := range entry {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func cartesianProduct(entry MatrixEntry, keys []string) []map[string]string {
	result := []map[string]string{{}}
	for _, k := range keys {
		var next []map[string]string
		for _, prev := range result {
			for _, val := range entry[k] {
				combo := make(map[string]string, len(prev)+1)
				for kk, vv := range prev {
					combo[kk] = vv
				}
				combo[k] = val
				next = append(next, combo)
			}
		}
		result = next
	}
	return result
}

func cloneJobForVariant(job JobConfig) JobConfig {
	v := job
	v.Matrix = nil
	vars := make(map[string]string, len(job.Variables))
	for k, val := range job.Variables {
		vars[k] = val
	}
	v.Variables = vars
	return v
}
