stages:
  - step 1
  - step 2

variables:
  BAR: "Im a global variable"
  FOO: "Im a global variable too!"

Test:
  stage: step 1
  image: alpine
  network:
    host_access: true
  cache:
    key: cache
    paths:
      - ".npm"
      - "node_modules"
  variables:
    FOO: BAR
    BAZ: EGGS
  script:
    - echo "Hello World"
    - echo $FOO
    - touch foo.txt
    - sleep 5
    - echo "Hello from txt file" >> foo.txt
    - echo $BAZ >> foo.txt
    - cat foo.txt

Test3:
  stage: step 2
  image: gradle:jdk23-corretto
  network:
    host_mode: true
  cache:
    key: gradle_build
    paths:
      - ".gradle"
      - "build"
  variables:
    FOO: "Overwrite the global variable FOO"
    BAZ: "Overwrite the global variable BAZ"
  script:
    - echo "Hello World"
    - echo $FOO
    - touch foo.txt
    - sleep 5
    - echo "Hello from txt file" >> foo.txt
    - echo $BAZ >> foo.txt
    - cat foo.txt

#Test2:
#  step: step 2
#  image: alpine
#  variables:
#    FOO: BAR
#    BAZ: EGGS
#  script:
#    - echo "Hello World from step 2"
#    - echo $FOO
#    - touch foo.txt
#    - sleep 5
#    - echo "Hello from txt file" >> foo.txt
#    - cat foo.txt
#    - sleep 5
#    - ls -la
